language: node_js

node_js:
  - "4.2.1"

sudo: false

before_script:
  - npm install -g mocha
  - npm install -g bower
  - npm install -g grunt-cli
  - npm install
  - bower install
  - node app.js &
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
